backend/code_coverage_backend/gcp.py
backend/tests/conftest.py

Needed to populate the redis database on the new production instance. Would also be useful on dev instances...
```
from code_coverage_backend.gcp import GCPCache
GCPCache().ingest_available_reports('mozilla-central')
```

backend: Ingest all the reports from a GCP Cache.

---

bot/code_coverage_bot/codecov.py

To fix [this case](https://tools.taskcluster.net/groups/SWbGlULxT1q8AL3Od7HiXQ/tasks/SWbGlULxT1q8AL3Od7HiXQ/runs/0/logs/public%2Flogs%2Flive.log) (from pulse listener logs)
That looks like a bad rebase :/

bot: Remove extra TC creds

---

bot/code_coverage_bot/codecov.py
bot/code_coverage_bot/grcov.py
bot/code_coverage_bot/uploader.py
bot/tests/test_grcov.py

The try execution branch used the default output format `coveralls`, which was not compatible anymore with the phabricator uploader.
So i fixed that by only generating covdir report in the main workflow, then limiting the grcov output formats to only those necessary by different parts of the bot:
* lcov for suite reports
* covdir for main workflow
* files for chunk_mapping
* coveralls+ for zero coverage
I then replaced the coveralls test case by their equivalent in covdir format.
I succesfully ran the [try failing tasks](https://tools.taskcluster.net/groups/KB1I4YHaQc-m35jUDGAM_w/tasks/KB1I4YHaQc-m35jUDGAM_w/details) on my computer
@marco-c We could remove coveralls+ support by using covdir in zero coverage instead. WDYT ?

Fix try branch in bot

---

bot/taskcluster-hook.json
bot/tools/restart_tasks.py

Replaces the `covdir_gen` script.
It takes a list of existing code coverage task id, uses their revision data.
I had to patch the taskcluster hookd definition to support setting the task name & group id when specified in the trigger payload.

Add restart tasks script.

---

frontend/src/index.js

Backport of https://github.com/mozilla/code-coverage-reports/pull/85

Fix getMonth usage.

---

.taskcluster.yml

To wrap up https://bugzilla.mozilla.org/show_bug.cgi?id=1566048

Deploy frontend on AWS S3

---

.isort.cfg
backend/code_coverage_backend/backend/__init__.py
bot/ci/bootstrap.sh
bot/code_coverage_bot/cli.py
bot/code_coverage_bot/utils.py
tools/code_coverage_tools/log.py
tools/requirements.txt

Needed for https://github.com/mozilla/grcov/pull/304

Fix sentry usage & report grcov errors.

---

bot/code_coverage_bot/artifacts.py
bot/code_coverage_bot/chunk_mapping.py
bot/code_coverage_bot/taskcluster.py
bot/tests/fixtures/build-android-test-ccov/opt.json
bot/tests/fixtures/build-linux64-ccov/debug.json
bot/tests/fixtures/build-win64-ccov/debug.json
bot/tests/fixtures/build-win64/debug.json
bot/tests/fixtures/test-linux64-ccov/debug-cppunit.json
bot/tests/fixtures/test-linux64-ccov/debug-firefox-ui-functional-remote-e10s.json
bot/tests/fixtures/test-linux64-ccov/debug-mochitest-1.json
bot/tests/fixtures/test-linux64-ccov/debug-mochitest-e10s-7.json
bot/tests/fixtures/test-linux64/debug-mochitest-1.json
bot/tests/fixtures/test-windows10-64-ccov/debug-cppunit.json
bot/tests/fixtures/test-windows10-64-ccov/debug-mochitest-1.json
bot/tests/fixtures/test-windows10-64-ccov/debug-mochitest-e10s-7.json
bot/tests/fixtures/test-windows10-64/debug-cppunit.json
bot/tests/fixtures/test_task_from_group.json
bot/tests/test_artifacts.py
bot/tests/test_chunk_mapping.py
bot/tests/test_taskcluster.py

bot: Build suite, chunk and platform from full task

---

frontend/src/base.html
frontend/src/common.js
frontend/src/index.js
frontend/src/route.js
frontend/src/style.css
frontend/src/zero_coverage_report.js

frontend: Support suite & platform filters

---

frontend/webpack.prod.js

To avoid building an [extra file with just comments](https://tools.taskcluster.net/groups/WkIv_dHKRKKubzHRJbq59A/tasks/I2AJ--9QR9-JjZaiuE1X7g/runs/0/logs/public%2Flogs%2Flive.log#L81) that crashes the deployment task (no content type detected)

frontend: Do not extract comments in separate files on release.

---

.taskcluster.yml

To ship on [code-coverage-events-prod](https://dashboard.heroku.com/apps/code-coverage-events-prod/activity)

Use short channel name on events Heroku & S3 deploy

---

backend/code_coverage_backend/api.py
backend/tests/conftest.py
backend/tests/test_api.py

While working on #165 i discovered that the `/v2/latest` endpoint was broken.
I fixed the issue (i think it's a bad rebase on my part), and added a unit test to avoid that mistake.

Fix /v2/latest endpoint

---

bot/code_coverage_bot/hooks/base.py
bot/code_coverage_bot/hooks/cron.py
bot/code_coverage_bot/hooks/repo.py
bot/taskcluster-hook-cron.json
bot/taskcluster-hook-repo.json

bot: Use project.relman Taskcluster routes on all hooks

---

events/code_coverage_events/workflow.py
events/tests/test_workflow.py

Do not use pulse messages from non gecko builds

---

backend/code_coverage_backend/backend/__init__.py
bot/code_coverage_bot/cli.py
events/Dockerfile
events/code_coverage_events/cli.py
events/requirements.txt
events/setup.py
tools/code_coverage_tools/log.py

- I replaced the release-services naming scheme by our own.
- The bot already works, i just simplified its name
- The backend just needed a simpler name + channel to activate papertrail
- The events needs to use the local code-coverage-tools logger instead of libmozevent + simpler name + channel

Fixes to publish logs on papertrail

---

frontend/src/base.html
frontend/src/index.js
frontend/src/style.scss

Fixes #188 
Also fixes a bug i introduced on #187 : uncovered lines are not shown anymore

Display number of hits on each line

---

frontend/src/common.js
frontend/src/index.js

While working on #189 I noticed that the source file retrieved from HGMO is not cached.
Also, we were always retrieving the latest version from MC, instead of using the current revision from the frontend.

frontend: Store file source in cache

---

backend/code_coverage_backend/api.py
backend/code_coverage_backend/config.py
backend/tests/test_coverage.py
bot/code_coverage_bot/phabricator.py
bot/tests/conftest.py
bot/tests/test_phabricator.py
tools/code_coverage_tools/__init__.py

Fixes #200 
I saw some warnings for valid `.h` and `.c` missing files, so it's still useful.

Check path is supported and not 3rd party before sending a warning

---

frontend/src/base.html
frontend/src/common.js
frontend/src/index.js
frontend/src/route.js
frontend/src/style.scss

It was a bit more complicated than I initially thought, as we cannot use the hash mechanism (we are already using it for navigation !).
So i intercept click on `a.scroll` links, and directly update the display, without triggering a data reload that would reset the full display.
I also cleaned up the `display` method a bit, by using dedicated views for the directory & file views (which makes more sense). It's in the first commit, and could be in a separate PR if needed.
[Demo on the current build](https://taskcluster-artifacts.net/Sjlbd6OvRn2zhwGbQnP2jQ/0/public/frontend/index.html#revision=latest&path=dom%2Fmedia%2FAsyncLogger.h&view=file&line=107)

Support linking to a specific line

---

bot/code_coverage_bot/taskcluster.py
bot/tests/test_artifacts.py
bot/tests/test_taskcluster.py

bot: Use taskcluster client library, fixes #12

---

tools/code_coverage_tools/taskcluster.py

[I noticed](https://tools.taskcluster.net/groups/Hvkv98Y8R6Gushs6LyyeFw/tasks/Hvkv98Y8R6Gushs6LyyeFw/runs/0/logs/public%2Flogs%2Flive.log) that taskcluster proxy ip is still resolved instead of using `taskcluster` hostname directly.

Remove old nix hack to read /etc/hosts for taskcluster proxy.

---

bot/code_coverage_bot/taskcluster.py
bot/tests/test_taskcluster.py

refs taskcluster/taskcluster-proxy#44

bot: Use public download url for artifacts

---

frontend/src/zero_coverage_report.js

To avoid a bug when clicking on any file in the zero coverage browser: [example](https://codecoverage-testing.stage.mozaws.net/#view=zero&revision=latest&path=gfx%2Fangle%2Fcheckout%2Fsrc%2FlibGLESv2)

Use file view on zero coverage

---

frontend/src/base.html

Reverts mozilla/code-coverage#295
I changed the wrong spot... This one should have been view=directory.

Revert "Fix opening a file from the zero coverage viewer"

---

bot/code_coverage_bot/chunk_mapping.py
bot/code_coverage_bot/taskcluster.py
bot/tests/fixtures/test-linux1804-64-ccov/opt-cppunit.json
bot/tests/fixtures/test-linux1804-64-ccov/opt-mochitest-1.json
bot/tests/test_chunk_mapping.py
bot/tests/test_taskcluster.py
events/code_coverage_events/workflow.py
events/tests/test_workflow.py
report/firefox_code_coverage/codecoverage.py
report/tests/test.py

Stop relying on the task name prefix to detect coverage tasks

---

events/code_coverage_events/workflow.py
events/tests/test_workflow.py

As soon as we find a coverage task in the task group, we can trigger the bot. We don't need to wait to find the build task.
Depends on #352.

Return the first coverage task we find in the task group

---

bot/ci/bootstrap.sh

bot: Use Mercurial with Python 3

---

report/firefox_code_coverage/codecoverage.py
report/tests/test.py

`python3 codecoverage.py /home/marco/Documenti/FD/mozilla-unified/ try ba48d133044788d596397fd56889ad3c0916b435 --grcov grcov --stats` was failing without this, as the try push only contained a Windows coverage build.

report: Support cases where a push doesn't contain a Linux coverage build

---

bot/code_coverage_bot/artifacts.py
bot/code_coverage_bot/hooks/base.py
bot/code_coverage_bot/taskcluster.py
bot/tests/conftest.py
bot/tests/fixtures/decision_task.json
bot/tests/fixtures/latest_decision.json
bot/tests/fixtures/latest_linux.json
bot/tests/fixtures/latest_win.json
bot/tests/test_artifacts.py
bot/tests/test_taskcluster.py

This is another improvement in line with #352. We finally have no hardcoded platform name and no hardcoded configuration (opt / debug), so we can e.g. freely switch between opt and debug.

Stop relying on task routes specific to platform and configuration

---

.taskcluster.yml
report/firefox_code_coverage/__init__.py
report/firefox_code_coverage/codecoverage.py
report/requirements.txt

Use taskcluster client library

---

report/firefox_code_coverage/codecoverage.py
report/tests/test.py

Use grcov html output

---

frontend/src/zero_coverage_report.js

Fixes #394
We were setting lastPushDate in zero_coverage_report.js, but then using last_push_date in base.html.

Fix the last push date variable name

---

.isort.cfg
.taskcluster.yml
report/ci-test.sh
report/firefox_code_coverage/codecoverage.py
report/requirements.txt
report/setup.py
report/tests/test.py

Upload HTML report as artifact

---

events/code_coverage_events/workflow.py

Removing retry function to use built-in task cluster retries
Issue ref: https://github.com/mozilla/code-coverage/issues/416

Removing retry function to use task cluster

---

frontend/src/base.html
frontend/src/style.scss
frontend/src/zero_coverage_report.js

Fixed #97 and deleted trailing white spaces according to Taskcluster's log.
------------------------------------------------------------------------------------------------------
https://youtu.be/xmY6yLb7gu4
Here is a demo. Hopefully, I understood correctly where the question mark box should be.
Explanation of what I have done:
Line 59 in zero_coverage_report.js: sets the variable needs_explanation to true for the filter, completely_uncovered.
Line 138 - 146 in base.html: add the tooltip if the filter needs explanation (i.e. completely_uncovered).
At the end of style.scss: I added the CSS for the tooltip (i.e. popup explanation box) using SASS format.
Let me know if you have any questions or feedback. Thanks.

Issue #97, add explanation box - 2nd PR

---

backend/code_coverage_backend/gcp.py
backend/code_coverage_backend/report.py
backend/tests/test_gcp.py

Set expiration for ingested reports

---

bot/tests/conftest.py
bot/tests/test_taskcluster.py

From 274.06s to 36.47s on my computer.

Do not wait in Taskcluster unit tests

---

bot/ci/bootstrap.sh
bot/code_coverage_bot/grcov.py
bot/tests/test_grcov.py

bot: Update grcov to version 0.5.10

---

frontend/src/index.js

Fixes #316 by incrementing the div ids (ie l0 becomes l1, l1 becomes l2....) of the line number fields by 1.

lines begin with 1

---

addon/webpack.config.js

Webpack 5 is more strict, so we have to use 'source-map'.

Set webpack configuration.devtool to 'source-map' instead of 'sourcemap'

---

bot/code_coverage_bot/hooks/crontrigger.py
bot/code_coverage_bot/trigger_missing.py
bot/setup.py
bot/tests/test_trigger_missing.py

Create a new command to trigger missing revisions to be run in a separate cron hook that runs more frequently

---

report/firefox_code_coverage/codecoverage.py

On my system trying to execute the command `grcov ...` raises an error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'grcov'
```
But using `./grcov` works just fine. Use the full path regardless to avoid this issue.

Use full path for downloaded grcov binary

---

bot/code_coverage_bot/hooks/base.py

I've done some basic testing in a Jupyter notebook, though not of the code in situ, as that's more work.  @marco-c I'm guessing this should be enough, but if not, let me know...

Log exception downloading artifacts stack (#1260)

---

frontend/src/base.html

Webpack `require()` is returning an object.  Dotting into the `default` property resolves the issue.  
It should also be possible to enable `file-loader` and set `{ esModule: false}`, though that seems like a larger potential impact.

Fix broken images by dotting into Module property #533

---

.taskcluster.yml

Reverts mozilla/code-coverage#1634
Tasks triggered by the hook are failing to load the Docker image, and the switch to GCP is the likely cause.

Revert "Bug 1798886 - Migrate code-coverage from AWS to GCP"

---

.pre-commit-config.yaml
backend/code_coverage_backend/backend/__init__.py
bot/code_coverage_bot/cli.py
events/code_coverage_events/cli.py
tools/code_coverage_tools/log.py
tools/requirements.txt

Fixes #1521 by bringing in the changes from:
- https://github.com/mozilla/code-review/pull/1253
- https://github.com/mozilla/code-review/pull/1276
- https://github.com/mozilla/code-review/pull/1333
- https://github.com/mozilla/code-review/pull/1365

Use sentry_sdk instead of raven and improve Sentry grouping

---

.taskcluster.yml

Reverts mozilla/code-coverage#2014
Similar reasoning as https://github.com/mozilla/task-boot/pull/388.

Revert "Remove unneeded legacy scope docker-worker:capability:privileged"

---

tools/requirements.txt

Reverts mozilla/code-coverage#2064
Fixes #2094

Revert "build(deps): bump sentry-sdk from 1.16.0 to 1.31.0 in /tools"

---

events/Dockerfile

Bumps python from 3.7-slim to 3.11-slim.
---
updated-dependencies:
- dependency-name: python dependency-type: direct:production

build(deps): bump python from 3.7-slim to 3.11-slim in /events

---

tools/requirements.txt

Reverts mozilla/code-coverage#2329
The update broke Sentry.

Revert "build(deps): bump sentry-sdk from 1.40.5 to 2.5.1 in /tools"

---

.taskcluster.yml

We (taskcluster team) intend to remove support for Ubuntu 22.04 in the near future.

Migrate from Ubuntu 22.04 to Ubuntu 24.04 in CI

---

.taskcluster.yml

In https://bugzilla.mozilla.org/show_bug.cgi?id=1907217 we're making scopes more explicit for branches. Because of this, pushes to branches not named in that repository will not be able to run. If this will be problematic, or we need to add more branches to this list, please let me know and we'll sort it out!

restrict on push builds to master and production in taskcluster

---

tools/code_coverage_tools/log.py
tools/requirements.txt

tools: Use modern sentry SDK
