tools/code_coverage_tools/taskcluster.py

Port of https://github.com/mozilla/code-review/pull/52

tools: Update taskcluster service loader.

---

bot/code_coverage_bot/uploader.py

@marco-c We should add integration tests to run the bot in MC & try mode on a specific revision. Mayeb disable publication with an option ?

bot: Fix encoding issue on GCP uploader

---

bot/ci/bootstrap.sh
bot/tests/test__system.py

bot: Use mercurial 5.1

---

tools/code_coverage_tools/log.py

Port from https://github.com/mozilla/code-review/pull/118
[Test issue on sentry](https://sentry.prod.mozaws.net/operations/code-coverage-bot/issues/6364850/?query=is:unresolved%20test)

tools: Add release & taskcluster infos in Sentry

---

bot/code_coverage_bot/notifier.py
bot/code_coverage_bot/phabricator.py
bot/tests/test_notifier.py

bot: Use phabricator url in low coverage mail

---

.taskcluster.yml
bot/taskcluster-hook-cron.json
bot/taskcluster-hook-repo.json

We need to update the roles before merging this.

Use relman-svc-* worker types instead of releng-svc-*

---

frontend/src/base.html

This commit modifies the tooltip text for the counters as mentioned in #214

Modify the tooltip message for counters

---

tools/requirements.txt

Limit async-timeout version

---

frontend/src/index.js

Fix file name rendering when dir ends with /

---

frontend/src/common.js

Always use directory view in navbar

---

frontend/src/common.js

Update zero coverage route,

---

tools/requirements.txt

Freeze tools dependencies

---

report/firefox_code_coverage/codecoverage.py

Fixes #243 
Still maintain `grcov_ver` file to validate unit tests

Download grcov from Taskcluster index

---

bot/requirements-dev.txt

This reverts commit 2333835336a0016332f3f91e6bf7040c8d3894f5.

Revert "Fix black setup on CI"

---

.taskcluster.yml

Same as https://github.com/mozilla/code-review/pull/538
Let's not break everything right now please.

Extend docker image lifetime to 6 months

---

bot/code_coverage_bot/hooks/cron.py
bot/taskcluster-hook-cron.json

Fixes #318
Once landed i'll make patches on ci-configuration.

Remove old releng Taskcluster routes

---

.taskcluster.yml

-the github diffing algo, doesn't show the right picture.

prevent CI on PR closure

---

frontend/src/style.scss

See issue https://github.com/mozilla/code-coverage/issues/488 for the details of this PR, and pull https://github.com/mozilla/code-coverage/pull/504 for another change preposed in the issue.

Match the style of the logo with the menu

---

bot/code_coverage_bot/taskcluster.py
bot/code_coverage_bot/uploader.py
report/firefox_code_coverage/codecoverage.py

#396 
Please let me know if any changes required! :)

exponential backoff with tenacity

---

bot/code_coverage_bot/taskcluster.py
bot/tests/fixtures/source-test-node-newtab-unit-tests-ccov.json
bot/tests/test_taskcluster.py

bot: Support parsing suite and chunk name from source-test tasks

---

tools/requirements.txt

Remove explicit requirement on urllib3

---

tools/code_coverage_tools/log.py

Use importlib.metadata instead of pkg_resources

---

frontend/package.json

Remove Node OpenSSL legacy provider
